### ISSUE TITLE
Failed to start a pure Kotlin app via `gradle run`

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-boot#1]
```
2022-10-28 14:33:01.994 [main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@418e7838{/,file:///home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/webapp/,STOPPED}
java.nio.file.NoSuchFileException: /home/mavi/work/my/vok/karibu10-helloworld-application/build/classes/java/main
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:831)
        at java.base/java.util.zip.ZipFile$CleanableResource$FinalizableResource.<init>(ZipFile.java:857)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:846)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
        at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:695)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:611)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:422)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:351)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:169)
        at org.eclipse.jetty.webapp.Configurations.preConfigure(Configurations.java:496)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:509)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:531)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.server.Server.start(Server.java:469)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
        at org.eclipse.jetty.server.Server.doStart(Server.java:414)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at com.github.mvysny.vaadinboot.VaadinBoot.start(VaadinBoot.java:171)
        at com.github.mvysny.vaadinboot.VaadinBoot.run(VaadinBoot.java:115)
        at com.example.karibudsl.MainKt.main(Main.kt:14)
``

**Comment by mvysny** [comment]
Workaround is to add one Java class to your project, to enforce creation of the `build/classes/java/main` folder. Apparently Jetty scans the classpath which contains a non-existing folder (probably passed in from Gradle).

**Comment by mvysny** [comment]
MetaInfConfiguration:200 reads the `System.getProperty("java.class.path")` which contains the classpath entries. Perhaps we should "fix" the property and remove non-existing entries.

**Comment by mvysny** [comment]
Yup, confirming that the following kotlin code fixes the issue:
```kotlin
    val classpath = System.getProperty("java.class.path")
        .split(File.pathSeparatorChar)
        .filter { File(it).exists() }
    System.setProperty("java.class.path", classpath.joinToString(File.pathSeparator))
```
